/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package learning;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Sridher
 */
public class SimpleCalculator extends javax.swing.JFrame {
    double a=0, b=0, result=0;
    int nextOperation = 0;
    int operator=0;
    /**
     * Creates new form SimpleCalculator
     */
    public SimpleCalculator() {
        image = new ImageIcon(getClass().getResource("/images/calculator.png")).getImage();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf1 = new javax.swing.JTextField();
        bbckspace = new javax.swing.JButton();
        bC = new javax.swing.JButton();
        bplus = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bminus = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bmulti = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bdec = new javax.swing.JButton();
        bequal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setIconImage(image);

        jPanel1.setBackground(new java.awt.Color(234, 234, 253));

        tf1.setEditable(false);
        tf1.setBackground(new java.awt.Color(255, 255, 255));
        tf1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tf1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tf1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf1.setEditable(false);

        bbckspace.setText("Backspace");

        bC.setText("C");

        bplus.setText("+");

        b7.setText("7");

        b8.setText("8");

        b9.setText("9");

        bminus.setText("-");

        b4.setText("4");

        b5.setText("5");

        b6.setText("6");

        bmulti.setText("*");

        b1.setText("1");

        b2.setText("2");

        b3.setText("3");

        bdiv.setText("/");

        b0.setText("0");

        bdec.setText(".");

        bequal.setText("=");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bdec, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bbckspace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bmulti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bequal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bminus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bplus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(tf1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bbckspace, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bplus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bminus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmulti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdec, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bequal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tf1.addKeyListener(new MyKeyListener());
        b1.addActionListener(new ButtonListener());
        b2.addActionListener(new ButtonListener());
        b3.addActionListener(new ButtonListener());
        b4.addActionListener(new ButtonListener());
        b5.addActionListener(new ButtonListener());
        b6.addActionListener(new ButtonListener());
        b7.addActionListener(new ButtonListener());
        b8.addActionListener(new ButtonListener());
        b9.addActionListener(new ButtonListener());
        b0.addActionListener(new ButtonListener());
        bplus.addActionListener(new ButtonListener());
        bminus.addActionListener(new ButtonListener());
        bmulti.addActionListener(new ButtonListener());
        bdiv.addActionListener(new ButtonListener());
        bdec.addActionListener(new ButtonListener());
        bbckspace.addActionListener(new ButtonListener());
        bC.addActionListener(new ButtonListener());
        bequal.addActionListener(new ButtonListener());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    class ButtonListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource()== b1){
                tf1.setText(nextOperation==1 ? "1" : tf1.getText().concat("1"));
                nextOperation=0;
            }
            if (e.getSource()== b2){
                tf1.setText(nextOperation==1 ? "2" : tf1.getText().concat("2"));
                nextOperation=0;
            }            
            if (e.getSource()== b3){
                tf1.setText(nextOperation==1 ? "3" : tf1.getText().concat("3"));
                nextOperation=0;
            }
            if (e.getSource()== b4){
                tf1.setText(nextOperation==1 ? "4" : tf1.getText().concat("4"));
                nextOperation=0;
            }
            if (e.getSource()== b5){
                tf1.setText(nextOperation==1 ? "5" : tf1.getText().concat("5"));
                nextOperation=0;
            }
            if (e.getSource()== b6){
                tf1.setText(nextOperation==1 ? "6" : tf1.getText().concat("6"));
                nextOperation=0;
            }
            if (e.getSource()== b7){
                tf1.setText(nextOperation==1 ? "7" : tf1.getText().concat("7"));
                nextOperation=0;
            }
            if (e.getSource()== b8){
                tf1.setText(nextOperation==1 ? "8" : tf1.getText().concat("8"));
                nextOperation=0;
            }
            if (e.getSource()== b9){
                tf1.setText(nextOperation==1 ? "9" : tf1.getText().concat("9"));
                nextOperation=0;
            }
            if (e.getSource()== b0){
                tf1.setText(nextOperation==1 ? "0" : tf1.getText().concat("0"));
                nextOperation=0;
            }
            if (e.getSource()== bdec){
                tf1.setText(nextOperation==1 ? "0.0" : tf1.getText().isEmpty() ? "0" : tf1.getText()+".");
                nextOperation=0;
            }            
            if (e.getSource()== bplus){
                a = Double.parseDouble((tf1.getText().isEmpty() ? "0" : tf1.getText()));
                operator = 1;
                tf1.setText("");
            }           
            if (e.getSource()== bminus){
                a = Double.parseDouble((tf1.getText().isEmpty() ? "0" : tf1.getText()));
                operator = 2;
                tf1.setText("");
            }

            if (e.getSource()== bmulti){
                a = Double.parseDouble((tf1.getText().isEmpty() ? "0" : tf1.getText()));
                operator = 3;
                tf1.setText("");
            } 
            if (e.getSource()== bdiv){
                a = Double.parseDouble((tf1.getText().isEmpty() ? "0" : tf1.getText()));
                operator = 4;
                tf1.setText("");
            }
            if (e.getSource()== bequal){
                b = Double.parseDouble((tf1.getText().isEmpty() ? "0" : tf1.getText()) );
                switch (operator){
                    case 1: {
                        result = a+ b;
                        break;
                    }
                    case 2: {
                        result = a- b;
                        break;
                    }
                    case 3: {
                        result = a* b;
                        break;
                    }
                    case 4: {
                        result = a/b;
                        break;
                    }
                }
                tf1.setText(""+result);
                nextOperation=1;
            }
            
            if (e.getSource()== bbckspace){
                String temp = tf1.getText();
                tf1.setText(temp.substring(0, temp.length()-1));
            }
            if (e.getSource()== bC){
                a=0;b=0;
                tf1.setText("");
            }
            
        }
        
    }
    
    
    private class MyKeyListener implements KeyListener {
        double a=0,b=0,result=0;
        int operator=0;
        @Override
        public void keyTyped(KeyEvent e) {

            if (((int) e.getKeyChar() >= 42 && (int) e.getKeyChar() <= 57) || (int) e.getKeyChar() == 8 || (int) e.getKeyChar() == 61 || (int) e.getKeyChar() == 10) {
                
                if ((int) e.getKeyChar() == 43) {
                    a = Double.parseDouble((tf1.getText().isEmpty() ? "0" : tf1.getText()));
                    operator = 1;
                    tf1.setText("");
                }
                else if ((int) e.getKeyChar() == 45) {
                    a = Double.parseDouble((tf1.getText().isEmpty() ? "0" : tf1.getText()));
                    operator = 2;
                    tf1.setText("");
                }
                else if ((int) e.getKeyChar() == 42) {
                    a = Double.parseDouble((tf1.getText().isEmpty() ? "0" : tf1.getText()));
                    operator = 3;
                    tf1.setText("");
                }
                else if ((int) e.getKeyChar() == 47) {
                    a = Double.parseDouble((tf1.getText().isEmpty() ? "0" : tf1.getText()));
                    operator = 3;
                    tf1.setText("");
                }
                else if ((int) e.getKeyChar() == 61 || (int) e.getKeyChar() == 10) {
                    b = Double.parseDouble((tf1.getText().isEmpty() ? "0" : tf1.getText()));
                    switch (operator) {
                        case 1: {
                            result = a + b;
                            break;
                        }
                        case 2: {
                            result = a - b;
                            break;
                        }
                        case 3: {
                            result = a * b;
                            break;
                        }
                        case 4: {
                            result = a / b;
                            break;
                        }
                    }
                    tf1.setText("" + result);
                    nextOperation = 1;
                }

                else if ((int) e.getKeyChar() == 8) {
                    String temp = tf1.getText();
                    tf1.setText(temp.substring(0, temp.length() - 1));
                }
                else {tf1.setText(nextOperation==1  ? ""+e.getKeyChar() : tf1.getText() + e.getKeyChar());}
            }
        }

        @Override
        public void keyPressed(KeyEvent e) {
            
        }

        @Override
        public void keyReleased(KeyEvent e) {
            
        }
        
    }
    
    
    public static void main(String args[]) {
        

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bC;
    private javax.swing.JButton bbckspace;
    private javax.swing.JButton bdec;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bequal;
    private javax.swing.JButton bminus;
    private javax.swing.JButton bmulti;
    private javax.swing.JButton bplus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
    private Image image=null;
}
